<?php

namespace Database\Seeders;

use App\Models\Account;
use App\Models\Accountsubgroup;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AccountSeeder extends Seeder
{

    public function run(): void
    {
        $name_1 = Accountsubgroup::where('name', 'DISPONIBILIDADES')->value('accountsubgroup_uuid');
        $name_2 = Accountsubgroup::where('name', 'EXIGIBLE')->value('accountsubgroup_uuid');
        $name_3 = Accountsubgroup::where('name', 'ACTIVO REALIZABLE O BIEN')->value('accountsubgroup_uuid');
        $name_4 = Accountsubgroup::where('name', 'PAGOS ANTICIPADOS')->value('accountsubgroup_uuid');
        $name_5 = Accountsubgroup::where('name', 'INVERSIONES TEMPORARIAS')->value('accountsubgroup_uuid');
        $name_6 = Accountsubgroup::where('name', 'OTROS ACTIVOS CORRIENTES')->value('accountsubgroup_uuid');
        $name_7 = Accountsubgroup::where('name', 'ACTIVO FIJO - BIENES DE USO, PROPIEDAD PLANTA')->value('accountsubgroup_uuid');
        $name_8 = Accountsubgroup::where('name', 'ACTIVOS INTANGIBLES')->value('accountsubgroup_uuid');
        $name_9 = Accountsubgroup::where('name', 'CARGOS DIFERIDOS')->value('accountsubgroup_uuid');
        $name_10 = Accountsubgroup::where('name', 'INVERSIONES A LARGO PLAZO')->value('accountsubgroup_uuid');
        $name_11 = Accountsubgroup::where('name', 'OBLIGACIONES COMERCIALES')->value('accountsubgroup_uuid');
        $name_12 = Accountsubgroup::where('name', 'OBLIGACIONES TRIBUTARIAS')->value('accountsubgroup_uuid');
        $name_13 = Accountsubgroup::where('name', 'OBLIGACIONES LABORALES')->value('accountsubgroup_uuid');
        $name_14 = Accountsubgroup::where('name', 'OTRAS CUENTAS POR PAGAR')->value('accountsubgroup_uuid');
        $name_15 = Accountsubgroup::where('name', 'INGRESOS ANTICIPADOS O DIFERIDOS')->value('accountsubgroup_uuid');
        $name_16 = Accountsubgroup::where('name', 'OBLIGACIONES A LARGO PLAZO')->value('accountsubgroup_uuid');
        $name_17 = Accountsubgroup::where('name', 'CAPITAL')->value('accountsubgroup_uuid');
        $name_18 = Accountsubgroup::where('name', 'RESERVAS')->value('accountsubgroup_uuid');
        $name_19 = Accountsubgroup::where('name', 'RESULTADOS ACUMULADOS')->value('accountsubgroup_uuid');
        $name_20 = Accountsubgroup::where('name', 'INGRESOS ORDINARIOS')->value('accountsubgroup_uuid');
        $name_21 = Accountsubgroup::where('name', 'INGRESOS NO ORDINARIOS')->value('accountsubgroup_uuid');
        $name_22 = Accountsubgroup::where('name', 'INGRESO NO OPERATIVO')->value('accountsubgroup_uuid');
        $name_23 = Accountsubgroup::where('name', 'COSTO DE BIENES Y SERVICIOS VENDIDOS')->value('accountsubgroup_uuid');
        $name_24 = Accountsubgroup::where('name', 'GASTOS ADMINISTRATIVOS')->value('accountsubgroup_uuid');
        $name_25 = Accountsubgroup::where('name', 'GASTOS DE COMERCIALIZACION')->value('accountsubgroup_uuid');
        $name_26 = Accountsubgroup::where('name', 'GASTOS FINANCIEROS')->value('accountsubgroup_uuid');
        $name_27 = Accountsubgroup::where('name', 'OTROS GASTOS')->value('accountsubgroup_uuid');
        $name_28 = Accountsubgroup::where('name', 'CUENTAS TRANSITORIAS')->value('accountsubgroup_uuid');
        $name_29 = Accountsubgroup::where('name', 'CUENTAS DE ORDEN DEUDORAS COMERCIALES')->value('accountsubgroup_uuid');
        $name_30 = Accountsubgroup::where('name', 'CUENTAS DE ORDEN ACREEDORAS COMERCIALES')->value('accountsubgroup_uuid');

        Account::create(['code' => 1010101, 'name' => 'CAJA MONEDA NACIONAL', 'description' => '', 'accountsubgroup_uuid' => $name_1, 'user_id' => 1]);
        Account::create(['code' => 1010102, 'name' => 'CAJA MONEDA EXTRANJERA', 'description' => '', 'accountsubgroup_uuid' => $name_1, 'user_id' => 1]);
        Account::create(['code' => 1010103, 'name' => 'BANCO MONEDA NACIONAL', 'description' => '', 'accountsubgroup_uuid' => $name_1, 'user_id' => 1]);
        Account::create(['code' => 1010104, 'name' => 'BANCO MONEDA EXTRANJERA', 'description' => '', 'accountsubgroup_uuid' => $name_1, 'user_id' => 1]);
        Account::create(['code' => 1010105, 'name' => 'CAJA CHICA O FONDO FIJO', 'description' => '', 'accountsubgroup_uuid' => $name_1, 'user_id' => 1]);
        Account::create(['code' => 1010201, 'name' => 'CUENTAS POR COBRAR', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010202, 'name' => 'DOCUMENTOS POR COBRAR', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010203, 'name' => 'DOCUMENTOS DESCONTADOS', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010204, 'name' => 'LETRAS POR COBRAR', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010205, 'name' => 'CUENTAS INCOBRABLES', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010206, 'name' => 'PREVISIÓN PARA CUENTAS INCOBRABLES', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010207, 'name' => 'CUENTAS POR COBRAR AL PERSONAL', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010208, 'name' => 'CUENTAS POR COBRAR A SOCIOS', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010209, 'name' => 'PRESTAMOS POR COBRAR', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010210, 'name' => 'ANTICIPO A PROVEEDORES', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010211, 'name' => 'ALQUILERES POR COBRAR', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010212, 'name' => 'INTERESES POR COBRAR', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010213, 'name' => 'COMISIONES POR COBRAR', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010214, 'name' => 'SEGUROS POR COBRAR', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010215, 'name' => 'ENTREGAS CON CARGO DE CUENTA', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010216, 'name' => 'DEPOSITOS EN GARANTIA', 'description' => '', 'accountsubgroup_uuid' => $name_2, 'user_id' => 1]);
        Account::create(['code' => 1010301, 'name' => 'INVENTARIO DE MERCADERIAS', 'description' => '', 'accountsubgroup_uuid' => $name_3, 'user_id' => 1]);
        Account::create(['code' => 1010302, 'name' => 'DETERIORO DE VALOR EN INVENTARIOS', 'description' => '', 'accountsubgroup_uuid' => $name_3, 'user_id' => 1]);
        Account::create(['code' => 1010303, 'name' => 'MERCADERIAS EN TRANSITO', 'description' => '', 'accountsubgroup_uuid' => $name_3, 'user_id' => 1]);
        Account::create(['code' => 1010304, 'name' => 'ALMACEN DE MATERIALES', 'description' => '', 'accountsubgroup_uuid' => $name_3, 'user_id' => 1]);
        Account::create(['code' => 1010305, 'name' => 'ALMACEN DE SUMINISTROS', 'description' => '', 'accountsubgroup_uuid' => $name_3, 'user_id' => 1]);
        Account::create(['code' => 1010401, 'name' => 'SEGUROS PAGADOS POR ANTICIPADO', 'description' => '', 'accountsubgroup_uuid' => $name_4, 'user_id' => 1]);
        Account::create(['code' => 1010402, 'name' => 'ALQUILERES PAGADOS POR ANTICIPADO', 'description' => '', 'accountsubgroup_uuid' => $name_4, 'user_id' => 1]);
        Account::create(['code' => 1010403, 'name' => 'INTERESES PAGADOS POR ANTICIPADO', 'description' => '', 'accountsubgroup_uuid' => $name_4, 'user_id' => 1]);
        Account::create(['code' => 1010404, 'name' => 'COMISIONES PAGADOS POR ANTICIPADO', 'description' => '', 'accountsubgroup_uuid' => $name_4, 'user_id' => 1]);
        Account::create(['code' => 1010405, 'name' => 'PUBLICIDAD PAGADOS POR ANTICIPADO', 'description' => '', 'accountsubgroup_uuid' => $name_4, 'user_id' => 1]);
        Account::create(['code' => 1010406, 'name' => 'SUELDOS Y SALARIOS PAGADOS POR ANTICIPADOS', 'description' => '', 'accountsubgroup_uuid' => $name_4, 'user_id' => 1]);
        Account::create(['code' => 1010501, 'name' => 'CAJA DE AHORRO MONEDA NACIONAL INVERSIONES FINANCIERAS', 'description' => '', 'accountsubgroup_uuid' => $name_5, 'user_id' => 1]);
        Account::create(['code' => 1010502, 'name' => 'CAJA DE AHORRO MONEDA EXTRANJERA INVERSIONES FINANCIERAS', 'description' => '', 'accountsubgroup_uuid' => $name_5, 'user_id' => 1]);
        Account::create(['code' => 1010503, 'name' => 'DEPÓSITOS A PLAZO FIJO INVERSIONES FINANCIERAS', 'description' => '', 'accountsubgroup_uuid' => $name_5, 'user_id' => 1]);
        Account::create(['code' => 1010504, 'name' => 'BONOS INVERSIONES FINANCIERAS', 'description' => '', 'accountsubgroup_uuid' => $name_5, 'user_id' => 1]);
        Account::create(['code' => 1010505, 'name' => 'CONTRATOS DE ANTICRETICO INVERSIONES NO FINANCIERAS', 'description' => '', 'accountsubgroup_uuid' => $name_5, 'user_id' => 1]);
        Account::create(['code' => 1010601, 'name' => 'CREDITO FISCAL IVA', 'description' => '', 'accountsubgroup_uuid' => $name_6, 'user_id' => 1]);
        Account::create(['code' => 1010602, 'name' => 'CREDITO FISCAL IVA DIFERIDO', 'description' => '', 'accountsubgroup_uuid' => $name_6, 'user_id' => 1]);
        Account::create(['code' => 1010603, 'name' => 'IUE POR COMPENSAR', 'description' => '', 'accountsubgroup_uuid' => $name_6, 'user_id' => 1]);
        Account::create(['code' => 1020101, 'name' => 'TERRENO', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020102, 'name' => 'EDIFICIO', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020103, 'name' => 'DEPRECIACIÓN ACUMULADA EDIFICIO', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020104, 'name' => 'EQUIPO DE OFICINA', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020105, 'name' => 'DEPRECIACIÓN ACUMULADA EQUIPO DE OFICINA', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020106, 'name' => 'MUEBLES Y ENSERES', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020107, 'name' => 'DEPRECIACIÓN ACUMULADA MUEBLES Y ENSERES', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020108, 'name' => 'MAQUINARIAS EN GENERAL', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020109, 'name' => 'DEPRECIACIÓN ACUMULADA MAQUINARIA EN GENERAL', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020110, 'name' => 'VEHÍCULOS', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020111, 'name' => 'DEPRECIACIÓN ACUMULADA VEHÍCULOS', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020112, 'name' => 'EQUIPO DE COMPUTACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020113, 'name' => 'DEPRECIACIÓN ACUMULADA EQUIPO DE COMPUTACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020114, 'name' => 'HERRAMIENTAS EN GENERAL', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020115, 'name' => 'DEPRECIACIÓN ACUMULADA HERRAMIENTAS', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020116, 'name' => 'OBRAS EN CONSTRUCCION', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020117, 'name' => 'ACTIVOS EN TRANSITO', 'description' => '', 'accountsubgroup_uuid' => $name_7, 'user_id' => 1]);
        Account::create(['code' => 1020201, 'name' => 'MARCAS DE FÁBRICA', 'description' => '', 'accountsubgroup_uuid' => $name_8, 'user_id' => 1]);
        Account::create(['code' => 1020202, 'name' => 'PATENTES DE INVENCIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_8, 'user_id' => 1]);
        Account::create(['code' => 1020203, 'name' => 'DERECHO DE LLAVE', 'description' => '', 'accountsubgroup_uuid' => $name_8, 'user_id' => 1]);
        Account::create(['code' => 1020204, 'name' => 'SOFTWARE COMPUTACIONAL', 'description' => '', 'accountsubgroup_uuid' => $name_8, 'user_id' => 1]);
        Account::create(['code' => 1020205, 'name' => 'AMORTIZACIÓN ACUM. MARCAS DE FÁBRICA', 'description' => '', 'accountsubgroup_uuid' => $name_8, 'user_id' => 1]);
        Account::create(['code' => 1020206, 'name' => 'AMORTIZACIÓN ACUM. PATENTES DE INVENCIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_8, 'user_id' => 1]);
        Account::create(['code' => 1020207, 'name' => 'AMORTIZACIÓN ACUM. DERECHO DE LLAVE', 'description' => '', 'accountsubgroup_uuid' => $name_8, 'user_id' => 1]);
        Account::create(['code' => 1020208, 'name' => 'AMORTIZACIÓN ACUM. SOFTWARE COMPUTACIONAL', 'description' => '', 'accountsubgroup_uuid' => $name_8, 'user_id' => 1]);
        Account::create(['code' => 1020301, 'name' => 'GASTOS DE ORGANIZACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_9, 'user_id' => 1]);
        Account::create(['code' => 1020302, 'name' => 'AMORTIZACIÓN ACUM. GASTOS DE ORGANIZACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_9, 'user_id' => 1]);
        Account::create(['code' => 1020303, 'name' => 'ESTUDIOS Y PROYECTOS', 'description' => '', 'accountsubgroup_uuid' => $name_9, 'user_id' => 1]);
        Account::create(['code' => 1020401, 'name' => 'ACCIONES EN OTRAS EMPRESAS', 'description' => '', 'accountsubgroup_uuid' => $name_10, 'user_id' => 1]);
        Account::create(['code' => 1020402, 'name' => 'BONOS DE EMPRESAS', 'description' => '', 'accountsubgroup_uuid' => $name_10, 'user_id' => 1]);
        Account::create(['code' => 1020403, 'name' => 'CERTIFICADOS DE APORTACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_10, 'user_id' => 1]);
        Account::create(['code' => 2010101, 'name' => 'CUENTAS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_11, 'user_id' => 1]);
        Account::create(['code' => 2010102, 'name' => 'DOCUMENTOS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_11, 'user_id' => 1]);
        Account::create(['code' => 2010103, 'name' => 'LETRAS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_11, 'user_id' => 1]);
        Account::create(['code' => 2010104, 'name' => 'ANTICIPO DE CLIENTES', 'description' => '', 'accountsubgroup_uuid' => $name_11, 'user_id' => 1]);
        Account::create(['code' => 2010105, 'name' => 'COMISION EN VENTAS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_11, 'user_id' => 1]);
        Account::create(['code' => 2010201, 'name' => 'DÉBITO FISCAL - IVA', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010202, 'name' => 'IMPUESTO A LAS TRANSACCIONES POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010203, 'name' => 'RET. I.T. POR PAGAR 3%', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010204, 'name' => 'RET. I.U.E. POR PAGAR 5%', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010205, 'name' => 'RET. RC-IVA POR PAGAR 13%', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010206, 'name' => 'RC-IVA POR PAGAR Planilla Impositiva', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010207, 'name' => 'I.U.E. POR PAGAR 25%', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010208, 'name' => 'IMPTO. A LA PROPIEDAD DE BIEN INMUEBLES POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010209, 'name' => 'IMPTO. A LA PROPIEDAD DE VEHICULOS AUTOM. POR', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010210, 'name' => 'IMPUESTO MUNICIPAL A LAS TRANSFERENCIAS POR', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010211, 'name' => 'PATENTES MUNICIPALES POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010212, 'name' => 'MULTAS E INTERES TRIBUTARIAS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_12, 'user_id' => 1]);
        Account::create(['code' => 2010301, 'name' => 'SUELDOS Y SALARIOS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_13, 'user_id' => 1]);
        Account::create(['code' => 2010302, 'name' => 'APORTE LABORAL SOLIDARIO AFP POR PAGAR 1% , 5%, 10%', 'description' => '', 'accountsubgroup_uuid' => $name_13, 'user_id' => 1]);
        Account::create(['code' => 2010303, 'name' => 'APORTE LABORAL AFP POR PAGAR AFPs 12,71%', 'description' => '', 'accountsubgroup_uuid' => $name_13, 'user_id' => 1]);
        Account::create(['code' => 2010304, 'name' => 'APORTE PATRONAL AFP POR PAGAR AFPs 6,71%', 'description' => '', 'accountsubgroup_uuid' => $name_13, 'user_id' => 1]);
        Account::create(['code' => 2010305, 'name' => 'APORTE PATRONAL CAJA DE SALUD POR PAGAR 10%', 'description' => '', 'accountsubgroup_uuid' => $name_13, 'user_id' => 1]);
        Account::create(['code' => 2010306, 'name' => 'PROVISIÓN PARA AGUINALDOS', 'description' => '', 'accountsubgroup_uuid' => $name_13, 'user_id' => 1]);
        Account::create(['code' => 2010307, 'name' => 'SUBSIDIOS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_13, 'user_id' => 1]);
        Account::create(['code' => 2010308, 'name' => 'FINIQUITOS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_13, 'user_id' => 1]);
        Account::create(['code' => 2010309, 'name' => 'PRIMA ANUAL POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_13, 'user_id' => 1]);
        Account::create(['code' => 2010310, 'name' => 'HONORARIOS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_13, 'user_id' => 1]);
        Account::create(['code' => 2010401, 'name' => 'ALQUILERES POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_14, 'user_id' => 1]);
        Account::create(['code' => 2010402, 'name' => 'SERVICIOS BASICOS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_14, 'user_id' => 1]);
        Account::create(['code' => 2010403, 'name' => 'INTERESES POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_14, 'user_id' => 1]);
        Account::create(['code' => 2010404, 'name' => 'SEGUROS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_14, 'user_id' => 1]);
        Account::create(['code' => 2010405, 'name' => 'COMISIONES POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_14, 'user_id' => 1]);
        Account::create(['code' => 2010406, 'name' => 'PUBLICIDAD POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_14, 'user_id' => 1]);
        Account::create(['code' => 2010407, 'name' => 'SERVICIO DE MANTENIMIENTO POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_14, 'user_id' => 1]);
        Account::create(['code' => 2010501, 'name' => 'ALQUILERES PERCIBIDOS POR ANTICIPADO', 'description' => '', 'accountsubgroup_uuid' => $name_15, 'user_id' => 1]);
        Account::create(['code' => 2010502, 'name' => 'INTERESES PERCIBIDOS POR ANTICIPADO', 'description' => '', 'accountsubgroup_uuid' => $name_15, 'user_id' => 1]);
        Account::create(['code' => 2010503, 'name' => 'COMISIONES PERCIBIDAS POR ANTICIPADO', 'description' => '', 'accountsubgroup_uuid' => $name_15, 'user_id' => 1]);
        Account::create(['code' => 2020101, 'name' => 'PRESTAMOS BANCARIOS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_16, 'user_id' => 1]);
        Account::create(['code' => 2020102, 'name' => 'PRESTAMOS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_16, 'user_id' => 1]);
        Account::create(['code' => 2020103, 'name' => 'BONOS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_16, 'user_id' => 1]);
        Account::create(['code' => 2020104, 'name' => 'HIPOTECAS POR PAGAR', 'description' => '', 'accountsubgroup_uuid' => $name_16, 'user_id' => 1]);
        Account::create(['code' => 2020105, 'name' => 'PREVISION PARA INDEMNIZACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_16, 'user_id' => 1]);
        Account::create(['code' => 3010101, 'name' => 'CAPITAL UNIPERSONAL', 'description' => '', 'accountsubgroup_uuid' => $name_17, 'user_id' => 1]);
        Account::create(['code' => 3010102, 'name' => 'CAPITAL SOCIAL', 'description' => '', 'accountsubgroup_uuid' => $name_17, 'user_id' => 1]);
        Account::create(['code' => 3010103, 'name' => 'AJUSTES DEL CAPITAL', 'description' => '', 'accountsubgroup_uuid' => $name_17, 'user_id' => 1]);
        Account::create(['code' => 3010104, 'name' => 'APORTES POR CAPITALIZAR', 'description' => '', 'accountsubgroup_uuid' => $name_17, 'user_id' => 1]);
        Account::create(['code' => 3010201, 'name' => 'RESERVA LEGAL', 'description' => '', 'accountsubgroup_uuid' => $name_18, 'user_id' => 1]);
        Account::create(['code' => 3010202, 'name' => 'RESERVA ESTATUTARIA', 'description' => '', 'accountsubgroup_uuid' => $name_18, 'user_id' => 1]);
        Account::create(['code' => 3010203, 'name' => 'RESERVA POR REVALÚO TÉCNICO DE ACTIVOS FIJOS', 'description' => '', 'accountsubgroup_uuid' => $name_18, 'user_id' => 1]);
        Account::create(['code' => 3010204, 'name' => 'AJUSTE DE RESERVAS PATRIMONIALES', 'description' => '', 'accountsubgroup_uuid' => $name_18, 'user_id' => 1]);

        Account::create(['code' => 3010301, 'name' => 'UTILIDAD DE LA GESTIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_19, 'user_id' => 1]);
        Account::create(['code' => 3010302, 'name' => 'PÉRDIDA DE LA GESTIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_19, 'user_id' => 1]);
        Account::create(['code' => 3010303, 'name' => 'RESULTADOS ACUMULADOS +/-', 'description' => '', 'accountsubgroup_uuid' => $name_19, 'user_id' => 1]);
        Account::create(['code' => 4010101, 'name' => 'VENTA DE MERCADERÍAS', 'description' => '', 'accountsubgroup_uuid' => $name_20, 'user_id' => 1]);
        Account::create(['code' => 4010102, 'name' => 'VENTA DE SERVICIOS', 'description' => '', 'accountsubgroup_uuid' => $name_20, 'user_id' => 1]);
        Account::create(['code' => 4010103, 'name' => 'DEVOLUCIONES EN VENTAS', 'description' => '', 'accountsubgroup_uuid' => $name_20, 'user_id' => 1]);
        Account::create(['code' => 4010201, 'name' => 'ALQUILERES PERCIBIDOS', 'description' => '', 'accountsubgroup_uuid' => $name_21, 'user_id' => 1]);
        Account::create(['code' => 4010202, 'name' => 'COMISIONES PERCIBIDAS', 'description' => '', 'accountsubgroup_uuid' => $name_21, 'user_id' => 1]);
        Account::create(['code' => 4010203, 'name' => 'INTERESES PERCIBIDOS', 'description' => '', 'accountsubgroup_uuid' => $name_21, 'user_id' => 1]);
        Account::create(['code' => 4010204, 'name' => 'DIVIDENDOS PERCIBIDOS', 'description' => '', 'accountsubgroup_uuid' => $name_21, 'user_id' => 1]);
        Account::create(['code' => 4010205, 'name' => 'VENTA DE DESPERDICIOS', 'description' => '', 'accountsubgroup_uuid' => $name_21, 'user_id' => 1]);
        Account::create(['code' => 4010206, 'name' => 'GANANCIA EN VENTA DE BIENES DE USO', 'description' => '', 'accountsubgroup_uuid' => $name_21, 'user_id' => 1]);
        Account::create(['code' => 4010207, 'name' => 'MULTAS DISCIPLINARIAS', 'description' => '', 'accountsubgroup_uuid' => $name_21, 'user_id' => 1]);
        Account::create(['code' => 4010208, 'name' => 'DONACIONES', 'description' => '', 'accountsubgroup_uuid' => $name_21, 'user_id' => 1]);
        Account::create(['code' => 4010209, 'name' => 'RENDIMIENTO EN INVERSIONES', 'description' => '', 'accountsubgroup_uuid' => $name_21, 'user_id' => 1]);
        Account::create(['code' => 4010210, 'name' => 'DESCUENTO RECIBIDO POR PRONTO PAGO', 'description' => '', 'accountsubgroup_uuid' => $name_21, 'user_id' => 1]);
        Account::create(['code' => 4010211, 'name' => 'REBAJAS Y BONIFICACIONES OBTENIDAS', 'description' => '', 'accountsubgroup_uuid' => $name_21, 'user_id' => 1]);
        Account::create(['code' => 4020101, 'name' => 'DIFERENCIA DE CAMBIO SALDO ACREEDOR', 'description' => '', 'accountsubgroup_uuid' => $name_22, 'user_id' => 1]);
        Account::create(['code' => 4020102, 'name' => 'DIFERENCIA POR REDONDEO S. ACREEDOR', 'description' => '', 'accountsubgroup_uuid' => $name_22, 'user_id' => 1]);
        Account::create(['code' => 4020103, 'name' => 'MANTENIMIENTO DE VALOR S. ACREEDOR', 'description' => '', 'accountsubgroup_uuid' => $name_22, 'user_id' => 1]);
        Account::create(['code' => 4020104, 'name' => 'AJUSTE POR INFLACIÓN Y TENENCIA DE  BIENES', 'description' => '', 'accountsubgroup_uuid' => $name_22, 'user_id' => 1]);

        Account::create(['code' => 5010101, 'name' => 'COSTO DE VENTAS', 'description' => '', 'accountsubgroup_uuid' => $name_23, 'user_id' => 1]);
        Account::create(['code' => 5010102, 'name' => 'COSTO DE SERVICIOS', 'description' => '', 'accountsubgroup_uuid' => $name_23, 'user_id' => 1]);
        Account::create(['code' => 5020101, 'name' => 'SUELDOS Y SALARIOS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020102, 'name' => 'APORTES PATRONALES', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020103, 'name' => 'AGUINALDOS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020104, 'name' => 'SUBSIDIOS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020105, 'name' => 'DESAHUCIOS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020106, 'name' => 'INDEMNIZACIONES', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020107, 'name' => 'VACACIONES', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020108, 'name' => 'PRIMAS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020109, 'name' => 'BONOS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020110, 'name' => 'ALQUILERES', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020111, 'name' => 'SEGUROS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020112, 'name' => 'HONORARIOS PROFESIONALES', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020113, 'name' => 'PASAJES Y VIÁTICOS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020114, 'name' => 'MATERIAL DE ESCRITORIO', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020115, 'name' => 'MATERIAL DE LIMPIEZA', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020116, 'name' => 'SERVICIOS BASICOS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020117, 'name' => 'SERVICIOS DE TELEFONIA E INTERNET', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020118, 'name' => 'GASTOS POR CAPACITACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020119, 'name' => 'GASTOS LEGALES', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020120, 'name' => 'GASTO DE MANTENIMIENTO Y REPARACION', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020121, 'name' => 'GASTOS DE COMUNICACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020122, 'name' => 'GASTOS DE TRANSPORTE', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020123, 'name' => 'GASTOS DE REPRESENTACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020124, 'name' => 'GASTOS POR FORMULARIOS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020125, 'name' => 'SERVICIO DE TE Y REFRIGERIO', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020126, 'name' => 'SERVICIOS DE AUDITORIA EXTERNA', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020127, 'name' => 'DONACIONES Y OBSEQUIOS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020128, 'name' => 'BOTIQUÍN DE MEDICINAS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020129, 'name' => 'IMPUESTOS A LAS PROPIEDADES DE BIENES', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020130, 'name' => 'PATENTES MUNICIPALES', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020131, 'name' => 'IMPUESTO A LAS UTILIDADES DE LAS EMPRESAS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020132, 'name' => 'INTERESES PAGADOS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020133, 'name' => 'DEPRECIACIÓN HERRAMIENTAS EN GENERAL', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020134, 'name' => 'DEPRECIACIÓN EQUIPO DE COMPUTACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020135, 'name' => 'DEPRECIACIÓN VEHÍCULOS', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020136, 'name' => 'DEPRECIACIÓN MAQUINARIAS EN GENERAL', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020137, 'name' => 'DEPRECIACIÓN MUEBLES Y ENSERES DE OFICINA', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020138, 'name' => 'DEPRECIACIÓN EQUIPO DE OFICINA', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020139, 'name' => 'DEPRECIACIÓN EDIFICIO', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020140, 'name' => 'AMORTIZACION GASTOS DE ORGANIZACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020141, 'name' => 'AMORTIZACIÓN MARCAS DE FABRICA', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020142, 'name' => 'AMORTIZACIÓN PATENTES DE INVENCIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);
        Account::create(['code' => 5020143, 'name' => 'AMORTIZACIÓN DERECHO DE LLAVE', 'description' => '', 'accountsubgroup_uuid' => $name_24, 'user_id' => 1]);

        Account::create(['code' => 5020201, 'name' => 'PUBLICIDAD Y PROPAGANDA', 'description' => '', 'accountsubgroup_uuid' => $name_25, 'user_id' => 1]);
        Account::create(['code' => 5020202, 'name' => 'COMISIÓN EN VENTAS', 'description' => '', 'accountsubgroup_uuid' => $name_25, 'user_id' => 1]);
        Account::create(['code' => 5020203, 'name' => 'IMPUESTO A LAS TRANSACCIONES', 'description' => '', 'accountsubgroup_uuid' => $name_25, 'user_id' => 1]);
        Account::create(['code' => 5020204, 'name' => 'MERMAS Y FALLAS EN MERCADERÍAS', 'description' => '', 'accountsubgroup_uuid' => $name_25, 'user_id' => 1]);
        Account::create(['code' => 5020205, 'name' => 'PERDIDA EN CUENTAS INCOBRABLES', 'description' => '', 'accountsubgroup_uuid' => $name_25, 'user_id' => 1]);
        Account::create(['code' => 5020206, 'name' => 'SUMINISTRO DE ALMACENES', 'description' => '', 'accountsubgroup_uuid' => $name_25, 'user_id' => 1]);
        Account::create(['code' => 5020207, 'name' => 'FLETE Y ALMACENAMIENTO', 'description' => '', 'accountsubgroup_uuid' => $name_25, 'user_id' => 1]);
        Account::create(['code' => 5020208, 'name' => 'DESCUENTOS OTORGADO POR PRONTO PAGO', 'description' => '', 'accountsubgroup_uuid' => $name_25, 'user_id' => 1]);
        Account::create(['code' => 5020209, 'name' => 'REBAJAS Y BONIFICACIONES CONCEDIDOS', 'description' => '', 'accountsubgroup_uuid' => $name_25, 'user_id' => 1]);

        Account::create(['code' => 5020301, 'name' => 'GASTOS POR CHEQUERA', 'description' => '', 'accountsubgroup_uuid' => $name_26, 'user_id' => 1]);
        Account::create(['code' => 5020302, 'name' => 'COMISIONES BANCARIAS', 'description' => '', 'accountsubgroup_uuid' => $name_26, 'user_id' => 1]);
        Account::create(['code' => 5020303, 'name' => 'INTERESES BANCARIOS', 'description' => '', 'accountsubgroup_uuid' => $name_26, 'user_id' => 1]);
        Account::create(['code' => 5020304, 'name' => 'IMPUESTO A LAS TRANSACCIONES FINANCIERAS', 'description' => '', 'accountsubgroup_uuid' => $name_26, 'user_id' => 1]);

        Account::create(['code' => 5030101, 'name' => 'PÉRDIDA EN VENTA DE ACTIVOS BIENES DE USO', 'description' => '', 'accountsubgroup_uuid' => $name_27, 'user_id' => 1]);
        Account::create(['code' => 5030102, 'name' => 'PÉRDIDA EN INVENTARIO DE MERCADERÍA', 'description' => '', 'accountsubgroup_uuid' => $name_27, 'user_id' => 1]);
        Account::create(['code' => 5030103, 'name' => 'PERDIDA POR SINIESTRO', 'description' => '', 'accountsubgroup_uuid' => $name_27, 'user_id' => 1]);
        Account::create(['code' => 5030104, 'name' => 'AJUSTE POR RECLASIFICACIÓN', 'description' => '', 'accountsubgroup_uuid' => $name_27, 'user_id' => 1]);
        Account::create(['code' => 5030105, 'name' => 'AJUSTE POR INFLACIÓN Y TENENCIA DE BIENES', 'description' => '', 'accountsubgroup_uuid' => $name_27, 'user_id' => 1]);
        Account::create(['code' => 5030106, 'name' => 'MANTENIMIENTO DE VALOR S. DEUDOR', 'description' => '', 'accountsubgroup_uuid' => $name_27, 'user_id' => 1]);
        Account::create(['code' => 5030107, 'name' => 'DIFERENCIA DE CAMBIO S. DEUDOR', 'description' => '', 'accountsubgroup_uuid' => $name_27, 'user_id' => 1]);
        Account::create(['code' => 5030108, 'name' => 'DIFERENCIA POR REDONDEO S. DEUDOR', 'description' => '', 'accountsubgroup_uuid' => $name_27, 'user_id' => 1]);
        Account::create(['code' => 5030109, 'name' => 'FALTANTE EN CAJA', 'description' => '', 'accountsubgroup_uuid' => $name_27, 'user_id' => 1]);

        Account::create(['code' => 5040101, 'name' => 'PERDIDAS Y GANANCIAS', 'description' => '', 'accountsubgroup_uuid' => $name_28, 'user_id' => 1]);

        Account::create(['code' => 6010101, 'name' => 'MERCADERIAS RECIBIDAS EN CONSIGNACION', 'description' => '', 'accountsubgroup_uuid' => $name_29, 'user_id' => 1]);
        Account::create(['code' => 6010102, 'name' => 'BIENES RECIBIDOS EN CUSTODIA', 'description' => '', 'accountsubgroup_uuid' => $name_29, 'user_id' => 1]);
        Account::create(['code' => 6010103, 'name' => 'BIENES RECIBIDOS EN GARANTIA', 'description' => '', 'accountsubgroup_uuid' => $name_29, 'user_id' => 1]);
        Account::create(['code' => 7010101, 'name' => 'CONSIGNANTES DE MERCADERIAS', 'description' => '', 'accountsubgroup_uuid' => $name_30, 'user_id' => 1]);
        Account::create(['code' => 7010102, 'name' => 'RESPONSABILIDAD POR BIENES EN CUSTODIA', 'description' => '', 'accountsubgroup_uuid' => $name_30, 'user_id' => 1]);
        Account::create(['code' => 7010103, 'name' => 'RESPONSABILIDAD POR BIENES EN GARANTIA', 'description' => '', 'accountsubgroup_uuid' => $name_30, 'user_id' => 1]);
    }
}
