<table>
    <thead>
    <tr>
        <th>{{__('word.sale.sheet.product')}}</th>
        <th>{{__('word.sale.sheet.observation')}}</th>
        <th>{{__('word.sale.sheet.name')}}</th>
        <th>{{__('word.sale.sheet.amount')}}</th>
        <th>{{__('word.sale.sheet.user')}}</th>
        <th>{{__('word.sale.sheet.updated_at')}}</th>
        <th>{{__('word.sale.sheet.updated_at')}}</th>
    </tr>
    </thead>
    <tbody>
    @foreach($sales as $item)
        <tr>
            <td>{{$item->format_products}}</td>
            <td>{{$item->format_observation}}</td>
            <td>{{$item->format_name}}</td>
            <td>{{$item->format_amount}}</td>
            <td>{{$item->format_user}}</td>
            <td>{{$item->format_created_at}}</td>
            <td>{{$item->format_updated_at}}</td>
        </tr>
    @endforeach
    </tbody>
</table>
