<table>
    <thead>
    <tr>
        <th>{{__('word.income.sheet.service')}}</th>
        <th>{{__('word.income.sheet.observation')}}</th>
        <th>{{__('word.income.sheet.input_name')}}</th>
        <th>{{__('word.income.sheet.input_amount')}}</th>
        <th>{{__('word.income.sheet.output_name')}}</th>
        <th>{{__('word.income.sheet.output_amount')}}</th>
        <th>{{__('word.income.sheet.user')}}</th>
        <th>{{__('word.income.sheet.created_at')}}</th>
        <th>{{__('word.income.sheet.updated_at')}}</th>
    </tr>
    </thead>
    <tbody>
    @foreach($incomes as $item)
        <tr>
            <td>{{$item->format_services}}</td>
            <td>{{$item->format_observation}}</td>
            <td>{{$item->format_input_name}}</td>
            <td>{{number_format($item->format_input_amount,2,'.','')}}</td>
            <td>{{$item->format_output_name}}</td>
            <td>{{number_format($item->format_output_amount,2,'.','')}}</td>
            <td>{{$item->format_user}}</td>
            <td>{{$item->format_created_at}}</td>
            <td>{{$item->format_updated_at}}</td>
        </tr>
    @endforeach
    </tbody>
</table>
